Mybranch
ClevertecFrontendLab/sprint1-harmmselution pull request #1
Opened 2023-01-28 13:39 UTC by harmmselution

2023-01-28 13:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674913571/content-window.png)

2023-01-28 13:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1674914140/content-window.png)

2023-01-28 13:57 UTC, klichkovskiy requested changes

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/book--page/book-page.jsx
> +      <div className={styles.greyComponent}>
![image](https://user-images.githubusercontent.com/62481116/215270051-c447aeac-c2a6-42b4-8ed0-c28725cd7186.png)
Исправить

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/book--page/book-page.jsx
> +      <div className={styles.greyComponent}>
Что это за отступы? Вернее их остутствие.
![image](https://user-images.githubusercontent.com/62481116/215270085-39d4c74f-9d45-44a3-a3ba-01a5dc3d95cb.png)

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/book--page/book-page.jsx
> +      <div className={styles.greyComponent}>
Исправь чтобы везде не было нулевых отсупов

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/main/main.jsx
> +const arrayOfBooks = [
![image](https://user-images.githubusercontent.com/62481116/215270142-72ef79d3-47cf-425e-adfa-80edb8f65972.png)
А чего роут не работает? Давай починим!

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/buttons/buttons.jsx
> +          <svg width='16' height='16' viewBox='0 0 16 16' fill='none' xmlns='http://www.w3.org/2000/svg'>
Давай лучше свг будем как обычные картинки экспортировать и вставлять. Это не правильно

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/card-container/card-container.jsx
> +      {/* <Link to='/book' className={styles.card1}>
Удаляй закомментированный код

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/main/main.jsx
> +  {
Это в константу вынеси!

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/nav-menu/nav-menu.jsx
> +const arrayOfCategories = [
Это тоже в отдельный файл в константе!

2023-01-28 13:57 UTC, klichkovskiy commented on src/components/rules/rules.jsx
> +            1. Идейные соображения высшего порядка,а также высокое качество позиционных исследований представляет собой
Так была же уже такая страница. Зачем второй раз тоже самое. Просто на разные роуты передай пропсом свои названия!

2023-01-29 16:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675009301/content-window.png)

2023-01-29 16:27 UTC, klichkovskiy requested changes

2023-01-29 16:27 UTC, klichkovskiy commented on src/components/book--page/book-page.module.scss
> +@media (max-width: 1130px) {
![image](https://user-images.githubusercontent.com/62481116/215340012-85034b35-4b36-4d2a-8802-5c487f824ab4.png)
Это что? Где отступы? Почему у тебя есть разрешения с отсупами 0px?

2023-01-29 16:27 UTC, klichkovskiy commented on src/index.js
> +            <Route path='/books' element={<Main />} />
Опять закомментированный код. Удаляй

2023-01-29 16:27 UTC, klichkovskiy commented on src/index.js
> +      <Routes>
Сделай нормальный отступы слева и права!

2023-01-29 17:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/harmmselution/1675013334/content-window.png)

2023-01-29 18:13 UTC, klichkovskiy approved these changes
По верстке все равно много замечаний. Не должно быть нулевых отступов ни на каких разрешения. Проверь в инструментах разработчика как ведет себя твое приложение на разных разрешениях. Пропускаю с большим авансом!

2023-01-29 18:16 UTC, merged